language: python
branches:
  only:
  - main
python:
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
install:
- python setup.py install
script:
- python setup.py test
after_failure:
- cat test.log
notifications:
  slack:
    secure: PY7GyhVBacVqytImbrcyKlDY/uVDTtOMMQ8bEDnhbH9XZA7nOD0dXsEffz93tA1ldJd1+0zsnt9itqdk4pYXBMTcZ6uWE5H2j7KIYylQa2A2Sj5GC3/KjrbFGfqMAXYs+rc9rrlqYkwjztu+bnNqTDnq0Y4Pw0YlMs23NT6GlMg=
env:
  global:
  - TWITTER_ENV: docnowdev
  - secure: d4+Uvcnuw9ZsYoufIY1CwAmBSFtW8ujduqlQR4Gwu+xBqNu7jSvbxHYOf//FRQxt5M7mg2NCURQSxtCgS0ItpUrFhhgb/ZCo+E0k/DU+dInvFhiNZxwfWYUimJTT8Y5xAJwYZYkGuxqkcEdVZoigT7QsVVb4VOOyUz1PcWzo5sI=
  - secure: VrDlKBaY9XPsZ3lPd/3+1ufsx5k8Av0EKhu71i6M5QULVBR6TrijafQlbfCwHXMtNB1QrDULSBm+qFjwDyrCg8b5FwbYlOO/Da7XKUNOGV70Ou2qHsuD9K3NbaRQMRxeOAkCkWUDA2VK0dLxkL81aRSWBiWmcsDqGk5L8YalU+A=
  - secure: CyEsIwbfQG2z6Wl0yNWlwFWT3IhXxM65ALF8yRvu6eSq7fCS8JwdV7TGNbP4hWK6V+TJ2H/lEK2lB3z2iGXEmO0iuz6LicOR1v6zIGiGU63lUTkDlNWne2DkpXN9T4eA9Jqk6Bxx8Q2l0Horo64i4mwh0bSd3UYgZXNRta9tfMM=
  - secure: cBDMI0EA/Y70pkd3Xpw11mmtDFfXa2looErH4UTZVaUKFtIf6M5Gnnoez5XW1f8LpM2OVQJo27w9CLbRmWjEl47OE0fYTgSVUKDJus5au0b+YBMk1iSk7dkZM2b+Nnyx2zS+bSh8FiBPvM3kx52FjmnxHmoJqayttR7XICHlZO8=
