name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/python3.txt

    - name: Test with pytest
      env:
        CONSUMER_KEY: ${{ secrets.consumer_key }}
        CONSUMER_SECRET: ${{ secrets.consumer_secret }}
        ACCESS_TOKEN: ${{ secrets.access_token }}
        ACCESS_TOKEN_SECRET: ${{ secrets.access_token_secret }}
      run: python setup.py test

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: docnow-build
        SLACK_ICON_EMOJI: ":test-tube:"
        SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
